openapi: 3.0.0
info:
  title: Append
  version: 1.0.0
paths:
  /api/upload/image:
    post:
      tags:
        - UploadServer
      description: "图片上传"
      summary: "图片上传"
      parameters:
        - in: header
          name: Authorization
          description: Authorization token
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: 图片地址
components:
  schemas:
    model.Link:
        type: object
        properties:
            type:
                type: string
                description: the type of link
            value:
                type: string
                description: the value of link
    model.Media:
        type: object
        properties:
            type:
                type: string
                description: IMAGE,VIDEO
            src:
                type: string
                description: the src of media