// Code generated by xapi. DO NOT EDIT.

package admin

import "github.com/gin-gonic/gin"

type adminImageServer struct {
	svc AdminImageServer
}

func (o *adminImageServer) List(c *gin.Context) (interface{}, error) {
	req := new(AdminImageListRequest)

	if err := c.ShouldBind(req); err != nil {
		return nil, err
	}

	resp, err := o.svc.List(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func RegisterAdminImageServer(r *gin.Engine, svc AdminImageServer, handle func(func(c *gin.Context) (interface{}, error)) gin.HandlerFunc, middlewares ...gin.HandlerFunc) {
	server := &adminImageServer{
		svc: svc,
	}

	r.POST("/admin/admin_image/list", append(middlewares, handle(server.List))...)
}
