// Code generated by xapi. DO NOT EDIT.

package admin

import "github.com/gin-gonic/gin"

type adminVideoServer struct {
	svc AdminVideoServer
}

func (o *adminVideoServer) List(c *gin.Context) (interface{}, error) {
	req := new(AdminVideoListRequest)

	if err := c.ShouldBind(req); err != nil {
		return nil, err
	}

	resp, err := o.svc.List(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func RegisterAdminVideoServer(r *gin.Engine, svc AdminVideoServer, handle func(func(c *gin.Context) (interface{}, error)) gin.HandlerFunc, middlewares ...gin.HandlerFunc) {
	server := &adminVideoServer{
		svc: svc,
	}

	r.POST("/admin/admin_video/list", append(middlewares, handle(server.List))...)
}
