// Code generated by xapi. DO NOT EDIT.

package admin

import "github.com/gin-gonic/gin"

type authServer struct {
	svc AuthServer
}

func (o *authServer) AuthLogin(c *gin.Context) (interface{}, error) {
	req := new(AuthLoginRequest)

	if err := c.ShouldBind(req); err != nil {
		return nil, err
	}

	resp, err := o.svc.AuthLogin(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (o *authServer) Captcha(c *gin.Context) (interface{}, error) {
	req := new(AuthCaptchaRequest)

	resp, err := o.svc.Captcha(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (o *authServer) AuthMenus(c *gin.Context) (interface{}, error) {
	req := new(AuthMenusRequest)

	resp, err := o.svc.AuthMenus(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func RegisterAuthServer(r *gin.Engine, svc AuthServer, handle func(func(c *gin.Context) (interface{}, error)) gin.HandlerFunc, middlewares ...gin.HandlerFunc) {
	server := &authServer{
		svc: svc,
	}

	r.POST("/admin/auth/login", append(middlewares, handle(server.AuthLogin))...)
	r.POST("/admin/auth/captcha", append(middlewares, handle(server.Captcha))...)
	r.POST("/admin/auth/menus", append(middlewares, handle(server.AuthMenus))...)
}
