// Code generated by xapi. DO NOT EDIT.

package admin

import "github.com/gin-gonic/gin"

type userServer struct {
	svc UserServer
}

func (o *userServer) List(c *gin.Context) (interface{}, error) {
	req := new(UserListRequest)

	if err := c.ShouldBind(req); err != nil {
		return nil, err
	}

	resp, err := o.svc.List(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (o *userServer) UpdateStatus(c *gin.Context) (interface{}, error) {
	req := new(UserUpdateStatusRequest)

	if err := c.ShouldBind(req); err != nil {
		return nil, err
	}

	resp, err := o.svc.UpdateStatus(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (o *userServer) Detail(c *gin.Context) (interface{}, error) {
	req := new(UserDetailRequest)

	if err := c.ShouldBind(req); err != nil {
		return nil, err
	}

	resp, err := o.svc.Detail(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (o *userServer) SafeQuestion(c *gin.Context) (interface{}, error) {
	req := new(UserSafeQuestionRequest)

	if err := c.ShouldBind(req); err != nil {
		return nil, err
	}

	resp, err := o.svc.SafeQuestion(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (o *userServer) ResetPayPassword(c *gin.Context) (interface{}, error) {
	req := new(UserResetPayPasswordRequest)

	if err := c.ShouldBind(req); err != nil {
		return nil, err
	}

	resp, err := o.svc.ResetPayPassword(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (o *userServer) Reset2fa(c *gin.Context) (interface{}, error) {
	req := new(UserReset2faRequest)

	if err := c.ShouldBind(req); err != nil {
		return nil, err
	}

	resp, err := o.svc.Reset2fa(c.Request.Context(), req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func RegisterUserServer(r *gin.Engine, svc UserServer, handle func(func(c *gin.Context) (interface{}, error)) gin.HandlerFunc, middlewares ...gin.HandlerFunc) {
	server := &userServer{
		svc: svc,
	}

	r.POST("/admin/user/list", append(middlewares, handle(server.List))...)
	r.POST("/admin/user/update_status", append(middlewares, handle(server.UpdateStatus))...)
	r.POST("/admin/user/detail", append(middlewares, handle(server.Detail))...)
	r.POST("/admin/user/safe_question", append(middlewares, handle(server.SafeQuestion))...)
	r.POST("/admin/user/reset_pay_password", append(middlewares, handle(server.ResetPayPassword))...)
	r.POST("/admin/user/reset_2fa", append(middlewares, handle(server.Reset2fa))...)
}
