// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setting

import (
	"app/services/internal/repo"
)

// Injectors from wire.go:

func NewSetting(repo2 *repo.SettingRepo) *Setting {
	settingSetting := &IntConfig{
		SettingRepo: repo2,
	}
	setting2 := &FloatConfig{
		SettingRepo: repo2,
	}
	setting3 := &StringConfig{
		SettingRepo: repo2,
	}
	setting4 := &FloatListConfig{
		SettingRepo: repo2,
	}
	setting5 := &StringListConfig{
		SettingRepo: repo2,
	}
	setting6 := &UsdtNetworkListConfig{
		SettingRepo: repo2,
	}
	setting7 := &LangTypeConfig{
		SettingRepo: repo2,
	}
	setting8 := &CurrencExchangeRateList{
		SettingRepo: repo2,
	}
	setting9 := &DepositCurrencyExchangeRateList{
		SettingRepo: repo2,
	}
	setting11 := &Setting{
		IntConfig:                               settingSetting,
		FloatConfig:                             setting2,
		StringConfig:                            setting3,
		FloatListConfig:                         setting4,
		StringListConfig:                        setting5,
		UsdtNetworkListConfig:                   setting6,
		LangTypeConfig:                          setting7,
		CurrencExchangeRate:                     setting8,
		DepositCurrencyExchangeRateList:         setting9,
	}
	return setting11
}
